import type { SelectOption } from "./components/ui/index.js";

export interface CountryCodeItem {
  code: string; // Dial code without +, e.g. "1", "7", "49"
  name: string;
  iso: string; // ISO 2-letter code, e.g. "US", "RU", "DE"
  flag: string;
  section?: string;
}

/**
 * Pinned & Popular Countries (US & Canada at top, Europe, Ukraine, etc.)
 */
export const POPULAR_COUNTRIES: CountryCodeItem[] = [
  {
    code: "1",
    name: "United States",
    iso: "US",
    flag: "🇺🇸",
  },
  {
    code: "1",
    name: "Canada",
    iso: "CA",
    flag: "🇨🇦",
  },
  {
    code: "44",
    name: "United Kingdom",
    iso: "GB",
    flag: "🇬🇧",
  },
  {
    code: "49",
    name: "Germany",
    iso: "DE",
    flag: "🇩🇪",
  },
  {
    code: "33",
    name: "France",
    iso: "FR",
    flag: "🇫🇷",
  },
  {
    code: "380",
    name: "Ukraine",
    iso: "UA",
    flag: "🇺🇦",
  },
  {
    code: "48",
    name: "Poland",
    iso: "PL",
    flag: "🇵🇱",
  },
  {
    code: "31",
    name: "Netherlands",
    iso: "NL",
    flag: "🇳🇱",
  },
  {
    code: "39",
    name: "Italy",
    iso: "IT",
    flag: "🇮🇹",
  },
  {
    code: "34",
    name: "Spain",
    iso: "ES",
    flag: "🇪🇸",
  },
  {
    code: "41",
    name: "Switzerland",
    iso: "CH",
    flag: "🇨🇭",
  },
  {
    code: "43",
    name: "Austria",
    iso: "AT",
    flag: "🇦🇹",
  },
  {
    code: "32",
    name: "Belgium",
    iso: "BE",
    flag: "🇧🇪",
  },
  {
    code: "46",
    name: "Sweden",
    iso: "SE",
    flag: "🇸🇪",
  },
  {
    code: "47",
    name: "Norway",
    iso: "NO",
    flag: "🇳🇴",
  },
  {
    code: "45",
    name: "Denmark",
    iso: "DK",
    flag: "🇩🇰",
  },
  {
    code: "358",
    name: "Finland",
    iso: "FI",
    flag: "🇫🇮",
  },
  {
    code: "353",
    name: "Ireland",
    iso: "IE",
    flag: "🇮🇪",
  },
  {
    code: "351",
    name: "Portugal",
    iso: "PT",
    flag: "🇵🇹",
  },
  {
    code: "420",
    name: "Czechia",
    iso: "CZ",
    flag: "🇨🇿",
  },
  {
    code: "40",
    name: "Romania",
    iso: "RO",
    flag: "🇷🇴",
  },
  {
    code: "30",
    name: "Greece",
    iso: "GR",
    flag: "🇬🇷",
  },
  {
    code: "36",
    name: "Hungary",
    iso: "HU",
    flag: "🇭🇺",
  },
  {
    code: "359",
    name: "Bulgaria",
    iso: "BG",
    flag: "🇧🇬",
  },
  {
    code: "421",
    name: "Slovakia",
    iso: "SK",
    flag: "🇸🇰",
  },
  {
    code: "385",
    name: "Croatia",
    iso: "HR",
    flag: "🇭🇷",
  },
  {
    code: "90",
    name: "Türkiye",
    iso: "TR",
    flag: "🇹🇷",
  },
  {
    code: "972",
    name: "Israel",
    iso: "IL",
    flag: "🇮🇱",
  },
  {
    code: "971",
    name: "United Arab Emirates",
    iso: "AE",
    flag: "🇦🇪",
  },
  {
    code: "966",
    name: "Saudi Arabia",
    iso: "SA",
    flag: "🇸🇦",
  },
  {
    code: "61",
    name: "Australia",
    iso: "AU",
    flag: "🇦🇺",
  },
  {
    code: "64",
    name: "New Zealand",
    iso: "NZ",
    flag: "🇳🇿",
  },
  {
    code: "81",
    name: "Japan",
    iso: "JP",
    flag: "🇯🇵",
  },
  {
    code: "82",
    name: "South Korea",
    iso: "KR",
    flag: "🇰🇷",
  },
  {
    code: "65",
    name: "Singapore",
    iso: "SG",
    flag: "🇸🇬",
  },
  {
    code: "55",
    name: "Brazil",
    iso: "BR",
    flag: "🇧🇷",
  },
  {
    code: "52",
    name: "Mexico",
    iso: "MX",
    flag: "🇲🇽",
  },
  {
    code: "54",
    name: "Argentina",
    iso: "AR",
    flag: "🇦🇷",
  },
  {
    code: "56",
    name: "Chile",
    iso: "CL",
    flag: "🇨🇱",
  },
  {
    code: "57",
    name: "Colombia",
    iso: "CO",
    flag: "🇨🇴",
  },
  {
    code: "7",
    name: "Kazakhstan",
    iso: "KZ",
    flag: "🇰🇿",
  },
  {
    code: "995",
    name: "Georgia",
    iso: "GE",
    flag: "🇬🇪",
  },
  {
    code: "374",
    name: "Armenia",
    iso: "AM",
    flag: "🇦🇲",
  },
  {
    code: "994",
    name: "Azerbaijan",
    iso: "AZ",
    flag: "🇦🇿",
  },
  {
    code: "998",
    name: "Uzbekistan",
    iso: "UZ",
    flag: "🇺🇿",
  },
  {
    code: "375",
    name: "Belarus",
    iso: "BY",
    flag: "🇧🇾",
  },
  {
    code: "7",
    name: "Russia",
    iso: "RU",
    flag: "🇷🇺",
  },
  {
    code: "86",
    name: "China",
    iso: "CN",
    flag: "🇨🇳",
  },
  {
    code: "91",
    name: "India",
    iso: "IN",
    flag: "🇮🇳",
  },
  {
    code: "66",
    name: "Thailand",
    iso: "TH",
    flag: "🇹🇭",
  },
  {
    code: "84",
    name: "Vietnam",
    iso: "VN",
    flag: "🇻🇳",
  },
  {
    code: "62",
    name: "Indonesia",
    iso: "ID",
    flag: "🇮🇩",
  },
  {
    code: "63",
    name: "Philippines",
    iso: "PH",
    flag: "🇵🇭",
  },
  {
    code: "60",
    name: "Malaysia",
    iso: "MY",
    flag: "🇲🇾",
  },
  {
    code: "27",
    name: "South Africa",
    iso: "ZA",
    flag: "🇿🇦",
  },
  {
    code: "20",
    name: "Egypt",
    iso: "EG",
    flag: "🇪🇬",
  },
];

/**
 * Remaining countries sorted alphabetically.
 */
export const REMAINING_COUNTRIES: CountryCodeItem[] = [
  {
    code: "93",
    name: "Afghanistan",
    iso: "AF",
    flag: "🇦🇫",
  },
  {
    code: "35818",
    name: "Åland Islands",
    iso: "AX",
    flag: "🇦🇽",
  },
  {
    code: "355",
    name: "Albania",
    iso: "AL",
    flag: "🇦🇱",
  },
  {
    code: "213",
    name: "Algeria",
    iso: "DZ",
    flag: "🇩🇿",
  },
  {
    code: "1684",
    name: "American Samoa",
    iso: "AS",
    flag: "🇦🇸",
  },
  {
    code: "376",
    name: "Andorra",
    iso: "AD",
    flag: "🇦🇩",
  },
  {
    code: "244",
    name: "Angola",
    iso: "AO",
    flag: "🇦🇴",
  },
  {
    code: "1264",
    name: "Anguilla",
    iso: "AI",
    flag: "🇦🇮",
  },
  {
    code: "1268",
    name: "Antigua & Barbuda",
    iso: "AG",
    flag: "🇦🇬",
  },
  {
    code: "297",
    name: "Aruba",
    iso: "AW",
    flag: "🇦🇼",
  },
  {
    code: "1242",
    name: "Bahamas",
    iso: "BS",
    flag: "🇧🇸",
  },
  {
    code: "973",
    name: "Bahrain",
    iso: "BH",
    flag: "🇧🇭",
  },
  {
    code: "880",
    name: "Bangladesh",
    iso: "BD",
    flag: "🇧🇩",
  },
  {
    code: "1246",
    name: "Barbados",
    iso: "BB",
    flag: "🇧🇧",
  },
  {
    code: "501",
    name: "Belize",
    iso: "BZ",
    flag: "🇧🇿",
  },
  {
    code: "229",
    name: "Benin",
    iso: "BJ",
    flag: "🇧🇯",
  },
  {
    code: "1441",
    name: "Bermuda",
    iso: "BM",
    flag: "🇧🇲",
  },
  {
    code: "975",
    name: "Bhutan",
    iso: "BT",
    flag: "🇧🇹",
  },
  {
    code: "591",
    name: "Bolivia",
    iso: "BO",
    flag: "🇧🇴",
  },
  {
    code: "387",
    name: "Bosnia & Herzegovina",
    iso: "BA",
    flag: "🇧🇦",
  },
  {
    code: "267",
    name: "Botswana",
    iso: "BW",
    flag: "🇧🇼",
  },
  {
    code: "246",
    name: "British Indian Ocean Territory",
    iso: "IO",
    flag: "🇮🇴",
  },
  {
    code: "1284",
    name: "British Virgin Islands",
    iso: "VG",
    flag: "🇻🇬",
  },
  {
    code: "673",
    name: "Brunei",
    iso: "BN",
    flag: "🇧🇳",
  },
  {
    code: "226",
    name: "Burkina Faso",
    iso: "BF",
    flag: "🇧🇫",
  },
  {
    code: "257",
    name: "Burundi",
    iso: "BI",
    flag: "🇧🇮",
  },
  {
    code: "855",
    name: "Cambodia",
    iso: "KH",
    flag: "🇰🇭",
  },
  {
    code: "237",
    name: "Cameroon",
    iso: "CM",
    flag: "🇨🇲",
  },
  {
    code: "238",
    name: "Cape Verde",
    iso: "CV",
    flag: "🇨🇻",
  },
  {
    code: "535",
    name: "Caribbean Netherlands",
    iso: "BQ",
    flag: "🇧🇶",
  },
  {
    code: "1345",
    name: "Cayman Islands",
    iso: "KY",
    flag: "🇰🇾",
  },
  {
    code: "236",
    name: "Central African Republic",
    iso: "CF",
    flag: "🇨🇫",
  },
  {
    code: "235",
    name: "Chad",
    iso: "TD",
    flag: "🇹🇩",
  },
  {
    code: "269",
    name: "Comoros",
    iso: "KM",
    flag: "🇰🇲",
  },
  {
    code: "242",
    name: "Congo - Brazzaville",
    iso: "CG",
    flag: "🇨🇬",
  },
  {
    code: "243",
    name: "Congo - Kinshasa",
    iso: "CD",
    flag: "🇨🇩",
  },
  {
    code: "682",
    name: "Cook Islands",
    iso: "CK",
    flag: "🇨🇰",
  },
  {
    code: "506",
    name: "Costa Rica",
    iso: "CR",
    flag: "🇨🇷",
  },
  {
    code: "225",
    name: "Côte d’Ivoire",
    iso: "CI",
    flag: "🇨🇮",
  },
  {
    code: "5999",
    name: "Curaçao",
    iso: "CW",
    flag: "🇨🇼",
  },
  {
    code: "357",
    name: "Cyprus",
    iso: "CY",
    flag: "🇨🇾",
  },
  {
    code: "253",
    name: "Djibouti",
    iso: "DJ",
    flag: "🇩🇯",
  },
  {
    code: "1767",
    name: "Dominica",
    iso: "DM",
    flag: "🇩🇲",
  },
  {
    code: "1849",
    name: "Dominican Republic",
    iso: "DO",
    flag: "🇩🇴",
  },
  {
    code: "593",
    name: "Ecuador",
    iso: "EC",
    flag: "🇪🇨",
  },
  {
    code: "503",
    name: "El Salvador",
    iso: "SV",
    flag: "🇸🇻",
  },
  {
    code: "240",
    name: "Equatorial Guinea",
    iso: "GQ",
    flag: "🇬🇶",
  },
  {
    code: "291",
    name: "Eritrea",
    iso: "ER",
    flag: "🇪🇷",
  },
  {
    code: "372",
    name: "Estonia",
    iso: "EE",
    flag: "🇪🇪",
  },
  {
    code: "268",
    name: "Eswatini",
    iso: "SZ",
    flag: "🇸🇿",
  },
  {
    code: "251",
    name: "Ethiopia",
    iso: "ET",
    flag: "🇪🇹",
  },
  {
    code: "500",
    name: "Falkland Islands",
    iso: "FK",
    flag: "🇫🇰",
  },
  {
    code: "298",
    name: "Faroe Islands",
    iso: "FO",
    flag: "🇫🇴",
  },
  {
    code: "679",
    name: "Fiji",
    iso: "FJ",
    flag: "🇫🇯",
  },
  {
    code: "594",
    name: "French Guiana",
    iso: "GF",
    flag: "🇬🇫",
  },
  {
    code: "689",
    name: "French Polynesia",
    iso: "PF",
    flag: "🇵🇫",
  },
  {
    code: "241",
    name: "Gabon",
    iso: "GA",
    flag: "🇬🇦",
  },
  {
    code: "220",
    name: "Gambia",
    iso: "GM",
    flag: "🇬🇲",
  },
  {
    code: "233",
    name: "Ghana",
    iso: "GH",
    flag: "🇬🇭",
  },
  {
    code: "350",
    name: "Gibraltar",
    iso: "GI",
    flag: "🇬🇮",
  },
  {
    code: "299",
    name: "Greenland",
    iso: "GL",
    flag: "🇬🇱",
  },
  {
    code: "1473",
    name: "Grenada",
    iso: "GD",
    flag: "🇬🇩",
  },
  {
    code: "590",
    name: "Guadeloupe",
    iso: "GP",
    flag: "🇬🇵",
  },
  {
    code: "1671",
    name: "Guam",
    iso: "GU",
    flag: "🇬🇺",
  },
  {
    code: "502",
    name: "Guatemala",
    iso: "GT",
    flag: "🇬🇹",
  },
  {
    code: "224",
    name: "Guinea",
    iso: "GN",
    flag: "🇬🇳",
  },
  {
    code: "245",
    name: "Guinea-Bissau",
    iso: "GW",
    flag: "🇬🇼",
  },
  {
    code: "592",
    name: "Guyana",
    iso: "GY",
    flag: "🇬🇾",
  },
  {
    code: "509",
    name: "Haiti",
    iso: "HT",
    flag: "🇭🇹",
  },
  {
    code: "504",
    name: "Honduras",
    iso: "HN",
    flag: "🇭🇳",
  },
  {
    code: "852",
    name: "Hong Kong SAR China",
    iso: "HK",
    flag: "🇭🇰",
  },
  {
    code: "354",
    name: "Iceland",
    iso: "IS",
    flag: "🇮🇸",
  },
  {
    code: "964",
    name: "Iraq",
    iso: "IQ",
    flag: "🇮🇶",
  },
  {
    code: "44",
    name: "Isle of Man",
    iso: "IM",
    flag: "🇮🇲",
  },
  {
    code: "1876",
    name: "Jamaica",
    iso: "JM",
    flag: "🇯🇲",
  },
  {
    code: "962",
    name: "Jordan",
    iso: "JO",
    flag: "🇯🇴",
  },
  {
    code: "254",
    name: "Kenya",
    iso: "KE",
    flag: "🇰🇪",
  },
  {
    code: "686",
    name: "Kiribati",
    iso: "KI",
    flag: "🇰🇮",
  },
  {
    code: "965",
    name: "Kuwait",
    iso: "KW",
    flag: "🇰🇼",
  },
  {
    code: "996",
    name: "Kyrgyzstan",
    iso: "KG",
    flag: "🇰🇬",
  },
  {
    code: "856",
    name: "Laos",
    iso: "LA",
    flag: "🇱🇦",
  },
  {
    code: "371",
    name: "Latvia",
    iso: "LV",
    flag: "🇱🇻",
  },
  {
    code: "961",
    name: "Lebanon",
    iso: "LB",
    flag: "🇱🇧",
  },
  {
    code: "266",
    name: "Lesotho",
    iso: "LS",
    flag: "🇱🇸",
  },
  {
    code: "231",
    name: "Liberia",
    iso: "LR",
    flag: "🇱🇷",
  },
  {
    code: "218",
    name: "Libya",
    iso: "LY",
    flag: "🇱🇾",
  },
  {
    code: "423",
    name: "Liechtenstein",
    iso: "LI",
    flag: "🇱🇮",
  },
  {
    code: "370",
    name: "Lithuania",
    iso: "LT",
    flag: "🇱🇹",
  },
  {
    code: "352",
    name: "Luxembourg",
    iso: "LU",
    flag: "🇱🇺",
  },
  {
    code: "853",
    name: "Macao SAR China",
    iso: "MO",
    flag: "🇲🇴",
  },
  {
    code: "261",
    name: "Madagascar",
    iso: "MG",
    flag: "🇲🇬",
  },
  {
    code: "265",
    name: "Malawi",
    iso: "MW",
    flag: "🇲🇼",
  },
  {
    code: "960",
    name: "Maldives",
    iso: "MV",
    flag: "🇲🇻",
  },
  {
    code: "223",
    name: "Mali",
    iso: "ML",
    flag: "🇲🇱",
  },
  {
    code: "356",
    name: "Malta",
    iso: "MT",
    flag: "🇲🇹",
  },
  {
    code: "692",
    name: "Marshall Islands",
    iso: "MH",
    flag: "🇲🇭",
  },
  {
    code: "596",
    name: "Martinique",
    iso: "MQ",
    flag: "🇲🇶",
  },
  {
    code: "222",
    name: "Mauritania",
    iso: "MR",
    flag: "🇲🇷",
  },
  {
    code: "230",
    name: "Mauritius",
    iso: "MU",
    flag: "🇲🇺",
  },
  {
    code: "262",
    name: "Mayotte",
    iso: "YT",
    flag: "🇾🇹",
  },
  {
    code: "691",
    name: "Micronesia",
    iso: "FM",
    flag: "🇫🇲",
  },
  {
    code: "373",
    name: "Moldova",
    iso: "MD",
    flag: "🇲🇩",
  },
  {
    code: "377",
    name: "Monaco",
    iso: "MC",
    flag: "🇲🇨",
  },
  {
    code: "976",
    name: "Mongolia",
    iso: "MN",
    flag: "🇲🇳",
  },
  {
    code: "382",
    name: "Montenegro",
    iso: "ME",
    flag: "🇲🇪",
  },
  {
    code: "1664",
    name: "Montserrat",
    iso: "MS",
    flag: "🇲🇸",
  },
  {
    code: "212",
    name: "Morocco",
    iso: "MA",
    flag: "🇲🇦",
  },
  {
    code: "258",
    name: "Mozambique",
    iso: "MZ",
    flag: "🇲🇿",
  },
  {
    code: "95",
    name: "Myanmar (Burma)",
    iso: "MM",
    flag: "🇲🇲",
  },
  {
    code: "264",
    name: "Namibia",
    iso: "NA",
    flag: "🇳🇦",
  },
  {
    code: "674",
    name: "Nauru",
    iso: "NR",
    flag: "🇳🇷",
  },
  {
    code: "977",
    name: "Nepal",
    iso: "NP",
    flag: "🇳🇵",
  },
  {
    code: "505",
    name: "Nicaragua",
    iso: "NI",
    flag: "🇳🇮",
  },
  {
    code: "227",
    name: "Niger",
    iso: "NE",
    flag: "🇳🇪",
  },
  {
    code: "234",
    name: "Nigeria",
    iso: "NG",
    flag: "🇳🇬",
  },
  {
    code: "683",
    name: "Niue",
    iso: "NU",
    flag: "🇳🇺",
  },
  {
    code: "672",
    name: "Norfolk Island",
    iso: "NF",
    flag: "🇳🇫",
  },
  {
    code: "389",
    name: "North Macedonia",
    iso: "MK",
    flag: "🇲🇰",
  },
  {
    code: "1670",
    name: "Northern Mariana Islands",
    iso: "MP",
    flag: "🇲🇵",
  },
  {
    code: "968",
    name: "Oman",
    iso: "OM",
    flag: "🇴🇲",
  },
  {
    code: "92",
    name: "Pakistan",
    iso: "PK",
    flag: "🇵🇰",
  },
  {
    code: "680",
    name: "Palau",
    iso: "PW",
    flag: "🇵🇼",
  },
  {
    code: "970",
    name: "Palestinian Territories",
    iso: "PS",
    flag: "🇵🇸",
  },
  {
    code: "507",
    name: "Panama",
    iso: "PA",
    flag: "🇵🇦",
  },
  {
    code: "675",
    name: "Papua New Guinea",
    iso: "PG",
    flag: "🇵🇬",
  },
  {
    code: "595",
    name: "Paraguay",
    iso: "PY",
    flag: "🇵🇾",
  },
  {
    code: "51",
    name: "Peru",
    iso: "PE",
    flag: "🇵🇪",
  },
  {
    code: "1787",
    name: "Puerto Rico",
    iso: "PR",
    flag: "🇵🇷",
  },
  {
    code: "974",
    name: "Qatar",
    iso: "QA",
    flag: "🇶🇦",
  },
  {
    code: "262",
    name: "Réunion",
    iso: "RE",
    flag: "🇷🇪",
  },
  {
    code: "250",
    name: "Rwanda",
    iso: "RW",
    flag: "🇷🇼",
  },
  {
    code: "685",
    name: "Samoa",
    iso: "WS",
    flag: "🇼🇸",
  },
  {
    code: "378",
    name: "San Marino",
    iso: "SM",
    flag: "🇸🇲",
  },
  {
    code: "239",
    name: "São Tomé & Príncipe",
    iso: "ST",
    flag: "🇸🇹",
  },
  {
    code: "221",
    name: "Senegal",
    iso: "SN",
    flag: "🇸🇳",
  },
  {
    code: "381",
    name: "Serbia",
    iso: "RS",
    flag: "🇷🇸",
  },
  {
    code: "248",
    name: "Seychelles",
    iso: "SC",
    flag: "🇸🇨",
  },
  {
    code: "232",
    name: "Sierra Leone",
    iso: "SL",
    flag: "🇸🇱",
  },
  {
    code: "1721",
    name: "Sint Maarten",
    iso: "SX",
    flag: "🇸🇽",
  },
  {
    code: "386",
    name: "Slovenia",
    iso: "SI",
    flag: "🇸🇮",
  },
  {
    code: "677",
    name: "Solomon Islands",
    iso: "SB",
    flag: "🇸🇧",
  },
  {
    code: "252",
    name: "Somalia",
    iso: "SO",
    flag: "🇸🇴",
  },
  {
    code: "94",
    name: "Sri Lanka",
    iso: "LK",
    flag: "🇱🇰",
  },
  {
    code: "590",
    name: "St. Barthélemy",
    iso: "BL",
    flag: "🇧🇱",
  },
  {
    code: "1869",
    name: "St. Kitts & Nevis",
    iso: "KN",
    flag: "🇰🇳",
  },
  {
    code: "1758",
    name: "St. Lucia",
    iso: "LC",
    flag: "🇱🇨",
  },
  {
    code: "590",
    name: "St. Martin",
    iso: "MF",
    flag: "🇲🇫",
  },
  {
    code: "508",
    name: "St. Pierre & Miquelon",
    iso: "PM",
    flag: "🇵🇲",
  },
  {
    code: "1784",
    name: "St. Vincent & Grenadines",
    iso: "VC",
    flag: "🇻🇨",
  },
  {
    code: "597",
    name: "Suriname",
    iso: "SR",
    flag: "🇸🇷",
  },
  {
    code: "4779",
    name: "Svalbard & Jan Mayen",
    iso: "SJ",
    flag: "🇸🇯",
  },
  {
    code: "886",
    name: "Taiwan",
    iso: "TW",
    flag: "🇹🇼",
  },
  {
    code: "992",
    name: "Tajikistan",
    iso: "TJ",
    flag: "🇹🇯",
  },
  {
    code: "255",
    name: "Tanzania",
    iso: "TZ",
    flag: "🇹🇿",
  },
  {
    code: "670",
    name: "Timor-Leste",
    iso: "TL",
    flag: "🇹🇱",
  },
  {
    code: "228",
    name: "Togo",
    iso: "TG",
    flag: "🇹🇬",
  },
  {
    code: "690",
    name: "Tokelau",
    iso: "TK",
    flag: "🇹🇰",
  },
  {
    code: "676",
    name: "Tonga",
    iso: "TO",
    flag: "🇹🇴",
  },
  {
    code: "1868",
    name: "Trinidad & Tobago",
    iso: "TT",
    flag: "🇹🇹",
  },
  {
    code: "216",
    name: "Tunisia",
    iso: "TN",
    flag: "🇹🇳",
  },
  {
    code: "993",
    name: "Turkmenistan",
    iso: "TM",
    flag: "🇹🇲",
  },
  {
    code: "1649",
    name: "Turks & Caicos Islands",
    iso: "TC",
    flag: "🇹🇨",
  },
  {
    code: "688",
    name: "Tuvalu",
    iso: "TV",
    flag: "🇹🇻",
  },
  {
    code: "1340",
    name: "U.S. Virgin Islands",
    iso: "VI",
    flag: "🇻🇮",
  },
  {
    code: "256",
    name: "Uganda",
    iso: "UG",
    flag: "🇺🇬",
  },
  {
    code: "598",
    name: "Uruguay",
    iso: "UY",
    flag: "🇺🇾",
  },
  {
    code: "678",
    name: "Vanuatu",
    iso: "VU",
    flag: "🇻🇺",
  },
  {
    code: "379",
    name: "Vatican City",
    iso: "VA",
    flag: "🇻🇦",
  },
  {
    code: "58",
    name: "Venezuela",
    iso: "VE",
    flag: "🇻🇪",
  },
  {
    code: "681",
    name: "Wallis & Futuna",
    iso: "WF",
    flag: "🇼🇫",
  },
  {
    code: "967",
    name: "Yemen",
    iso: "YE",
    flag: "🇾🇪",
  },
  {
    code: "260",
    name: "Zambia",
    iso: "ZM",
    flag: "🇿🇲",
  },
  {
    code: "263",
    name: "Zimbabwe",
    iso: "ZW",
    flag: "🇿🇼",
  },
  {
    code: "687",
    name: "新喀里多尼亚",
    iso: "NCL",
    flag: "🌐",
  },
];

/**
 * All 232 countries ordered with Popular first, followed by remaining countries alphabetically.
 */
export const ALL_COUNTRIES_ORDERED: CountryCodeItem[] = [
  {
    code: "1",
    name: "United States",
    iso: "US",
    flag: "🇺🇸",
    section: "Popular",
  },
  {
    code: "1",
    name: "Canada",
    iso: "CA",
    flag: "🇨🇦",
    section: "Popular",
  },
  {
    code: "44",
    name: "United Kingdom",
    iso: "GB",
    flag: "🇬🇧",
    section: "Popular",
  },
  {
    code: "49",
    name: "Germany",
    iso: "DE",
    flag: "🇩🇪",
    section: "Popular",
  },
  {
    code: "33",
    name: "France",
    iso: "FR",
    flag: "🇫🇷",
    section: "Popular",
  },
  {
    code: "380",
    name: "Ukraine",
    iso: "UA",
    flag: "🇺🇦",
    section: "Popular",
  },
  {
    code: "48",
    name: "Poland",
    iso: "PL",
    flag: "🇵🇱",
    section: "Popular",
  },
  {
    code: "31",
    name: "Netherlands",
    iso: "NL",
    flag: "🇳🇱",
    section: "Popular",
  },
  {
    code: "39",
    name: "Italy",
    iso: "IT",
    flag: "🇮🇹",
    section: "Popular",
  },
  {
    code: "34",
    name: "Spain",
    iso: "ES",
    flag: "🇪🇸",
    section: "Popular",
  },
  {
    code: "41",
    name: "Switzerland",
    iso: "CH",
    flag: "🇨🇭",
    section: "Popular",
  },
  {
    code: "43",
    name: "Austria",
    iso: "AT",
    flag: "🇦🇹",
    section: "Popular",
  },
  {
    code: "32",
    name: "Belgium",
    iso: "BE",
    flag: "🇧🇪",
    section: "Popular",
  },
  {
    code: "46",
    name: "Sweden",
    iso: "SE",
    flag: "🇸🇪",
    section: "Popular",
  },
  {
    code: "47",
    name: "Norway",
    iso: "NO",
    flag: "🇳🇴",
    section: "Popular",
  },
  {
    code: "45",
    name: "Denmark",
    iso: "DK",
    flag: "🇩🇰",
    section: "Popular",
  },
  {
    code: "358",
    name: "Finland",
    iso: "FI",
    flag: "🇫🇮",
    section: "Popular",
  },
  {
    code: "353",
    name: "Ireland",
    iso: "IE",
    flag: "🇮🇪",
    section: "Popular",
  },
  {
    code: "351",
    name: "Portugal",
    iso: "PT",
    flag: "🇵🇹",
    section: "Popular",
  },
  {
    code: "420",
    name: "Czechia",
    iso: "CZ",
    flag: "🇨🇿",
    section: "Popular",
  },
  {
    code: "40",
    name: "Romania",
    iso: "RO",
    flag: "🇷🇴",
    section: "Popular",
  },
  {
    code: "30",
    name: "Greece",
    iso: "GR",
    flag: "🇬🇷",
    section: "Popular",
  },
  {
    code: "36",
    name: "Hungary",
    iso: "HU",
    flag: "🇭🇺",
    section: "Popular",
  },
  {
    code: "359",
    name: "Bulgaria",
    iso: "BG",
    flag: "🇧🇬",
    section: "Popular",
  },
  {
    code: "421",
    name: "Slovakia",
    iso: "SK",
    flag: "🇸🇰",
    section: "Popular",
  },
  {
    code: "385",
    name: "Croatia",
    iso: "HR",
    flag: "🇭🇷",
    section: "Popular",
  },
  {
    code: "90",
    name: "Türkiye",
    iso: "TR",
    flag: "🇹🇷",
    section: "Popular",
  },
  {
    code: "972",
    name: "Israel",
    iso: "IL",
    flag: "🇮🇱",
    section: "Popular",
  },
  {
    code: "971",
    name: "United Arab Emirates",
    iso: "AE",
    flag: "🇦🇪",
    section: "Popular",
  },
  {
    code: "966",
    name: "Saudi Arabia",
    iso: "SA",
    flag: "🇸🇦",
    section: "Popular",
  },
  {
    code: "61",
    name: "Australia",
    iso: "AU",
    flag: "🇦🇺",
    section: "Popular",
  },
  {
    code: "64",
    name: "New Zealand",
    iso: "NZ",
    flag: "🇳🇿",
    section: "Popular",
  },
  {
    code: "81",
    name: "Japan",
    iso: "JP",
    flag: "🇯🇵",
    section: "Popular",
  },
  {
    code: "82",
    name: "South Korea",
    iso: "KR",
    flag: "🇰🇷",
    section: "Popular",
  },
  {
    code: "65",
    name: "Singapore",
    iso: "SG",
    flag: "🇸🇬",
    section: "Popular",
  },
  {
    code: "55",
    name: "Brazil",
    iso: "BR",
    flag: "🇧🇷",
    section: "Popular",
  },
  {
    code: "52",
    name: "Mexico",
    iso: "MX",
    flag: "🇲🇽",
    section: "Popular",
  },
  {
    code: "54",
    name: "Argentina",
    iso: "AR",
    flag: "🇦🇷",
    section: "Popular",
  },
  {
    code: "56",
    name: "Chile",
    iso: "CL",
    flag: "🇨🇱",
    section: "Popular",
  },
  {
    code: "57",
    name: "Colombia",
    iso: "CO",
    flag: "🇨🇴",
    section: "Popular",
  },
  {
    code: "7",
    name: "Kazakhstan",
    iso: "KZ",
    flag: "🇰🇿",
    section: "Popular",
  },
  {
    code: "995",
    name: "Georgia",
    iso: "GE",
    flag: "🇬🇪",
    section: "Popular",
  },
  {
    code: "374",
    name: "Armenia",
    iso: "AM",
    flag: "🇦🇲",
    section: "Popular",
  },
  {
    code: "994",
    name: "Azerbaijan",
    iso: "AZ",
    flag: "🇦🇿",
    section: "Popular",
  },
  {
    code: "998",
    name: "Uzbekistan",
    iso: "UZ",
    flag: "🇺🇿",
    section: "Popular",
  },
  {
    code: "375",
    name: "Belarus",
    iso: "BY",
    flag: "🇧🇾",
    section: "Popular",
  },
  {
    code: "7",
    name: "Russia",
    iso: "RU",
    flag: "🇷🇺",
    section: "Popular",
  },
  {
    code: "86",
    name: "China",
    iso: "CN",
    flag: "🇨🇳",
    section: "Popular",
  },
  {
    code: "91",
    name: "India",
    iso: "IN",
    flag: "🇮🇳",
    section: "Popular",
  },
  {
    code: "66",
    name: "Thailand",
    iso: "TH",
    flag: "🇹🇭",
    section: "Popular",
  },
  {
    code: "84",
    name: "Vietnam",
    iso: "VN",
    flag: "🇻🇳",
    section: "Popular",
  },
  {
    code: "62",
    name: "Indonesia",
    iso: "ID",
    flag: "🇮🇩",
    section: "Popular",
  },
  {
    code: "63",
    name: "Philippines",
    iso: "PH",
    flag: "🇵🇭",
    section: "Popular",
  },
  {
    code: "60",
    name: "Malaysia",
    iso: "MY",
    flag: "🇲🇾",
    section: "Popular",
  },
  {
    code: "27",
    name: "South Africa",
    iso: "ZA",
    flag: "🇿🇦",
    section: "Popular",
  },
  {
    code: "20",
    name: "Egypt",
    iso: "EG",
    flag: "🇪🇬",
    section: "Popular",
  },
  {
    code: "93",
    name: "Afghanistan",
    iso: "AF",
    flag: "🇦🇫",
    section: "All Countries (A-Z)",
  },
  {
    code: "35818",
    name: "Åland Islands",
    iso: "AX",
    flag: "🇦🇽",
    section: "All Countries (A-Z)",
  },
  {
    code: "355",
    name: "Albania",
    iso: "AL",
    flag: "🇦🇱",
    section: "All Countries (A-Z)",
  },
  {
    code: "213",
    name: "Algeria",
    iso: "DZ",
    flag: "🇩🇿",
    section: "All Countries (A-Z)",
  },
  {
    code: "1684",
    name: "American Samoa",
    iso: "AS",
    flag: "🇦🇸",
    section: "All Countries (A-Z)",
  },
  {
    code: "376",
    name: "Andorra",
    iso: "AD",
    flag: "🇦🇩",
    section: "All Countries (A-Z)",
  },
  {
    code: "244",
    name: "Angola",
    iso: "AO",
    flag: "🇦🇴",
    section: "All Countries (A-Z)",
  },
  {
    code: "1264",
    name: "Anguilla",
    iso: "AI",
    flag: "🇦🇮",
    section: "All Countries (A-Z)",
  },
  {
    code: "1268",
    name: "Antigua & Barbuda",
    iso: "AG",
    flag: "🇦🇬",
    section: "All Countries (A-Z)",
  },
  {
    code: "297",
    name: "Aruba",
    iso: "AW",
    flag: "🇦🇼",
    section: "All Countries (A-Z)",
  },
  {
    code: "1242",
    name: "Bahamas",
    iso: "BS",
    flag: "🇧🇸",
    section: "All Countries (A-Z)",
  },
  {
    code: "973",
    name: "Bahrain",
    iso: "BH",
    flag: "🇧🇭",
    section: "All Countries (A-Z)",
  },
  {
    code: "880",
    name: "Bangladesh",
    iso: "BD",
    flag: "🇧🇩",
    section: "All Countries (A-Z)",
  },
  {
    code: "1246",
    name: "Barbados",
    iso: "BB",
    flag: "🇧🇧",
    section: "All Countries (A-Z)",
  },
  {
    code: "501",
    name: "Belize",
    iso: "BZ",
    flag: "🇧🇿",
    section: "All Countries (A-Z)",
  },
  {
    code: "229",
    name: "Benin",
    iso: "BJ",
    flag: "🇧🇯",
    section: "All Countries (A-Z)",
  },
  {
    code: "1441",
    name: "Bermuda",
    iso: "BM",
    flag: "🇧🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "975",
    name: "Bhutan",
    iso: "BT",
    flag: "🇧🇹",
    section: "All Countries (A-Z)",
  },
  {
    code: "591",
    name: "Bolivia",
    iso: "BO",
    flag: "🇧🇴",
    section: "All Countries (A-Z)",
  },
  {
    code: "387",
    name: "Bosnia & Herzegovina",
    iso: "BA",
    flag: "🇧🇦",
    section: "All Countries (A-Z)",
  },
  {
    code: "267",
    name: "Botswana",
    iso: "BW",
    flag: "🇧🇼",
    section: "All Countries (A-Z)",
  },
  {
    code: "246",
    name: "British Indian Ocean Territory",
    iso: "IO",
    flag: "🇮🇴",
    section: "All Countries (A-Z)",
  },
  {
    code: "1284",
    name: "British Virgin Islands",
    iso: "VG",
    flag: "🇻🇬",
    section: "All Countries (A-Z)",
  },
  {
    code: "673",
    name: "Brunei",
    iso: "BN",
    flag: "🇧🇳",
    section: "All Countries (A-Z)",
  },
  {
    code: "226",
    name: "Burkina Faso",
    iso: "BF",
    flag: "🇧🇫",
    section: "All Countries (A-Z)",
  },
  {
    code: "257",
    name: "Burundi",
    iso: "BI",
    flag: "🇧🇮",
    section: "All Countries (A-Z)",
  },
  {
    code: "855",
    name: "Cambodia",
    iso: "KH",
    flag: "🇰🇭",
    section: "All Countries (A-Z)",
  },
  {
    code: "237",
    name: "Cameroon",
    iso: "CM",
    flag: "🇨🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "238",
    name: "Cape Verde",
    iso: "CV",
    flag: "🇨🇻",
    section: "All Countries (A-Z)",
  },
  {
    code: "535",
    name: "Caribbean Netherlands",
    iso: "BQ",
    flag: "🇧🇶",
    section: "All Countries (A-Z)",
  },
  {
    code: "1345",
    name: "Cayman Islands",
    iso: "KY",
    flag: "🇰🇾",
    section: "All Countries (A-Z)",
  },
  {
    code: "236",
    name: "Central African Republic",
    iso: "CF",
    flag: "🇨🇫",
    section: "All Countries (A-Z)",
  },
  {
    code: "235",
    name: "Chad",
    iso: "TD",
    flag: "🇹🇩",
    section: "All Countries (A-Z)",
  },
  {
    code: "269",
    name: "Comoros",
    iso: "KM",
    flag: "🇰🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "242",
    name: "Congo - Brazzaville",
    iso: "CG",
    flag: "🇨🇬",
    section: "All Countries (A-Z)",
  },
  {
    code: "243",
    name: "Congo - Kinshasa",
    iso: "CD",
    flag: "🇨🇩",
    section: "All Countries (A-Z)",
  },
  {
    code: "682",
    name: "Cook Islands",
    iso: "CK",
    flag: "🇨🇰",
    section: "All Countries (A-Z)",
  },
  {
    code: "506",
    name: "Costa Rica",
    iso: "CR",
    flag: "🇨🇷",
    section: "All Countries (A-Z)",
  },
  {
    code: "225",
    name: "Côte d’Ivoire",
    iso: "CI",
    flag: "🇨🇮",
    section: "All Countries (A-Z)",
  },
  {
    code: "5999",
    name: "Curaçao",
    iso: "CW",
    flag: "🇨🇼",
    section: "All Countries (A-Z)",
  },
  {
    code: "357",
    name: "Cyprus",
    iso: "CY",
    flag: "🇨🇾",
    section: "All Countries (A-Z)",
  },
  {
    code: "253",
    name: "Djibouti",
    iso: "DJ",
    flag: "🇩🇯",
    section: "All Countries (A-Z)",
  },
  {
    code: "1767",
    name: "Dominica",
    iso: "DM",
    flag: "🇩🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "1849",
    name: "Dominican Republic",
    iso: "DO",
    flag: "🇩🇴",
    section: "All Countries (A-Z)",
  },
  {
    code: "593",
    name: "Ecuador",
    iso: "EC",
    flag: "🇪🇨",
    section: "All Countries (A-Z)",
  },
  {
    code: "503",
    name: "El Salvador",
    iso: "SV",
    flag: "🇸🇻",
    section: "All Countries (A-Z)",
  },
  {
    code: "240",
    name: "Equatorial Guinea",
    iso: "GQ",
    flag: "🇬🇶",
    section: "All Countries (A-Z)",
  },
  {
    code: "291",
    name: "Eritrea",
    iso: "ER",
    flag: "🇪🇷",
    section: "All Countries (A-Z)",
  },
  {
    code: "372",
    name: "Estonia",
    iso: "EE",
    flag: "🇪🇪",
    section: "All Countries (A-Z)",
  },
  {
    code: "268",
    name: "Eswatini",
    iso: "SZ",
    flag: "🇸🇿",
    section: "All Countries (A-Z)",
  },
  {
    code: "251",
    name: "Ethiopia",
    iso: "ET",
    flag: "🇪🇹",
    section: "All Countries (A-Z)",
  },
  {
    code: "500",
    name: "Falkland Islands",
    iso: "FK",
    flag: "🇫🇰",
    section: "All Countries (A-Z)",
  },
  {
    code: "298",
    name: "Faroe Islands",
    iso: "FO",
    flag: "🇫🇴",
    section: "All Countries (A-Z)",
  },
  {
    code: "679",
    name: "Fiji",
    iso: "FJ",
    flag: "🇫🇯",
    section: "All Countries (A-Z)",
  },
  {
    code: "594",
    name: "French Guiana",
    iso: "GF",
    flag: "🇬🇫",
    section: "All Countries (A-Z)",
  },
  {
    code: "689",
    name: "French Polynesia",
    iso: "PF",
    flag: "🇵🇫",
    section: "All Countries (A-Z)",
  },
  {
    code: "241",
    name: "Gabon",
    iso: "GA",
    flag: "🇬🇦",
    section: "All Countries (A-Z)",
  },
  {
    code: "220",
    name: "Gambia",
    iso: "GM",
    flag: "🇬🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "233",
    name: "Ghana",
    iso: "GH",
    flag: "🇬🇭",
    section: "All Countries (A-Z)",
  },
  {
    code: "350",
    name: "Gibraltar",
    iso: "GI",
    flag: "🇬🇮",
    section: "All Countries (A-Z)",
  },
  {
    code: "299",
    name: "Greenland",
    iso: "GL",
    flag: "🇬🇱",
    section: "All Countries (A-Z)",
  },
  {
    code: "1473",
    name: "Grenada",
    iso: "GD",
    flag: "🇬🇩",
    section: "All Countries (A-Z)",
  },
  {
    code: "590",
    name: "Guadeloupe",
    iso: "GP",
    flag: "🇬🇵",
    section: "All Countries (A-Z)",
  },
  {
    code: "1671",
    name: "Guam",
    iso: "GU",
    flag: "🇬🇺",
    section: "All Countries (A-Z)",
  },
  {
    code: "502",
    name: "Guatemala",
    iso: "GT",
    flag: "🇬🇹",
    section: "All Countries (A-Z)",
  },
  {
    code: "224",
    name: "Guinea",
    iso: "GN",
    flag: "🇬🇳",
    section: "All Countries (A-Z)",
  },
  {
    code: "245",
    name: "Guinea-Bissau",
    iso: "GW",
    flag: "🇬🇼",
    section: "All Countries (A-Z)",
  },
  {
    code: "592",
    name: "Guyana",
    iso: "GY",
    flag: "🇬🇾",
    section: "All Countries (A-Z)",
  },
  {
    code: "509",
    name: "Haiti",
    iso: "HT",
    flag: "🇭🇹",
    section: "All Countries (A-Z)",
  },
  {
    code: "504",
    name: "Honduras",
    iso: "HN",
    flag: "🇭🇳",
    section: "All Countries (A-Z)",
  },
  {
    code: "852",
    name: "Hong Kong SAR China",
    iso: "HK",
    flag: "🇭🇰",
    section: "All Countries (A-Z)",
  },
  {
    code: "354",
    name: "Iceland",
    iso: "IS",
    flag: "🇮🇸",
    section: "All Countries (A-Z)",
  },
  {
    code: "964",
    name: "Iraq",
    iso: "IQ",
    flag: "🇮🇶",
    section: "All Countries (A-Z)",
  },
  {
    code: "44",
    name: "Isle of Man",
    iso: "IM",
    flag: "🇮🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "1876",
    name: "Jamaica",
    iso: "JM",
    flag: "🇯🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "962",
    name: "Jordan",
    iso: "JO",
    flag: "🇯🇴",
    section: "All Countries (A-Z)",
  },
  {
    code: "254",
    name: "Kenya",
    iso: "KE",
    flag: "🇰🇪",
    section: "All Countries (A-Z)",
  },
  {
    code: "686",
    name: "Kiribati",
    iso: "KI",
    flag: "🇰🇮",
    section: "All Countries (A-Z)",
  },
  {
    code: "965",
    name: "Kuwait",
    iso: "KW",
    flag: "🇰🇼",
    section: "All Countries (A-Z)",
  },
  {
    code: "996",
    name: "Kyrgyzstan",
    iso: "KG",
    flag: "🇰🇬",
    section: "All Countries (A-Z)",
  },
  {
    code: "856",
    name: "Laos",
    iso: "LA",
    flag: "🇱🇦",
    section: "All Countries (A-Z)",
  },
  {
    code: "371",
    name: "Latvia",
    iso: "LV",
    flag: "🇱🇻",
    section: "All Countries (A-Z)",
  },
  {
    code: "961",
    name: "Lebanon",
    iso: "LB",
    flag: "🇱🇧",
    section: "All Countries (A-Z)",
  },
  {
    code: "266",
    name: "Lesotho",
    iso: "LS",
    flag: "🇱🇸",
    section: "All Countries (A-Z)",
  },
  {
    code: "231",
    name: "Liberia",
    iso: "LR",
    flag: "🇱🇷",
    section: "All Countries (A-Z)",
  },
  {
    code: "218",
    name: "Libya",
    iso: "LY",
    flag: "🇱🇾",
    section: "All Countries (A-Z)",
  },
  {
    code: "423",
    name: "Liechtenstein",
    iso: "LI",
    flag: "🇱🇮",
    section: "All Countries (A-Z)",
  },
  {
    code: "370",
    name: "Lithuania",
    iso: "LT",
    flag: "🇱🇹",
    section: "All Countries (A-Z)",
  },
  {
    code: "352",
    name: "Luxembourg",
    iso: "LU",
    flag: "🇱🇺",
    section: "All Countries (A-Z)",
  },
  {
    code: "853",
    name: "Macao SAR China",
    iso: "MO",
    flag: "🇲🇴",
    section: "All Countries (A-Z)",
  },
  {
    code: "261",
    name: "Madagascar",
    iso: "MG",
    flag: "🇲🇬",
    section: "All Countries (A-Z)",
  },
  {
    code: "265",
    name: "Malawi",
    iso: "MW",
    flag: "🇲🇼",
    section: "All Countries (A-Z)",
  },
  {
    code: "960",
    name: "Maldives",
    iso: "MV",
    flag: "🇲🇻",
    section: "All Countries (A-Z)",
  },
  {
    code: "223",
    name: "Mali",
    iso: "ML",
    flag: "🇲🇱",
    section: "All Countries (A-Z)",
  },
  {
    code: "356",
    name: "Malta",
    iso: "MT",
    flag: "🇲🇹",
    section: "All Countries (A-Z)",
  },
  {
    code: "692",
    name: "Marshall Islands",
    iso: "MH",
    flag: "🇲🇭",
    section: "All Countries (A-Z)",
  },
  {
    code: "596",
    name: "Martinique",
    iso: "MQ",
    flag: "🇲🇶",
    section: "All Countries (A-Z)",
  },
  {
    code: "222",
    name: "Mauritania",
    iso: "MR",
    flag: "🇲🇷",
    section: "All Countries (A-Z)",
  },
  {
    code: "230",
    name: "Mauritius",
    iso: "MU",
    flag: "🇲🇺",
    section: "All Countries (A-Z)",
  },
  {
    code: "262",
    name: "Mayotte",
    iso: "YT",
    flag: "🇾🇹",
    section: "All Countries (A-Z)",
  },
  {
    code: "691",
    name: "Micronesia",
    iso: "FM",
    flag: "🇫🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "373",
    name: "Moldova",
    iso: "MD",
    flag: "🇲🇩",
    section: "All Countries (A-Z)",
  },
  {
    code: "377",
    name: "Monaco",
    iso: "MC",
    flag: "🇲🇨",
    section: "All Countries (A-Z)",
  },
  {
    code: "976",
    name: "Mongolia",
    iso: "MN",
    flag: "🇲🇳",
    section: "All Countries (A-Z)",
  },
  {
    code: "382",
    name: "Montenegro",
    iso: "ME",
    flag: "🇲🇪",
    section: "All Countries (A-Z)",
  },
  {
    code: "1664",
    name: "Montserrat",
    iso: "MS",
    flag: "🇲🇸",
    section: "All Countries (A-Z)",
  },
  {
    code: "212",
    name: "Morocco",
    iso: "MA",
    flag: "🇲🇦",
    section: "All Countries (A-Z)",
  },
  {
    code: "258",
    name: "Mozambique",
    iso: "MZ",
    flag: "🇲🇿",
    section: "All Countries (A-Z)",
  },
  {
    code: "95",
    name: "Myanmar (Burma)",
    iso: "MM",
    flag: "🇲🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "264",
    name: "Namibia",
    iso: "NA",
    flag: "🇳🇦",
    section: "All Countries (A-Z)",
  },
  {
    code: "674",
    name: "Nauru",
    iso: "NR",
    flag: "🇳🇷",
    section: "All Countries (A-Z)",
  },
  {
    code: "977",
    name: "Nepal",
    iso: "NP",
    flag: "🇳🇵",
    section: "All Countries (A-Z)",
  },
  {
    code: "505",
    name: "Nicaragua",
    iso: "NI",
    flag: "🇳🇮",
    section: "All Countries (A-Z)",
  },
  {
    code: "227",
    name: "Niger",
    iso: "NE",
    flag: "🇳🇪",
    section: "All Countries (A-Z)",
  },
  {
    code: "234",
    name: "Nigeria",
    iso: "NG",
    flag: "🇳🇬",
    section: "All Countries (A-Z)",
  },
  {
    code: "683",
    name: "Niue",
    iso: "NU",
    flag: "🇳🇺",
    section: "All Countries (A-Z)",
  },
  {
    code: "672",
    name: "Norfolk Island",
    iso: "NF",
    flag: "🇳🇫",
    section: "All Countries (A-Z)",
  },
  {
    code: "389",
    name: "North Macedonia",
    iso: "MK",
    flag: "🇲🇰",
    section: "All Countries (A-Z)",
  },
  {
    code: "1670",
    name: "Northern Mariana Islands",
    iso: "MP",
    flag: "🇲🇵",
    section: "All Countries (A-Z)",
  },
  {
    code: "968",
    name: "Oman",
    iso: "OM",
    flag: "🇴🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "92",
    name: "Pakistan",
    iso: "PK",
    flag: "🇵🇰",
    section: "All Countries (A-Z)",
  },
  {
    code: "680",
    name: "Palau",
    iso: "PW",
    flag: "🇵🇼",
    section: "All Countries (A-Z)",
  },
  {
    code: "970",
    name: "Palestinian Territories",
    iso: "PS",
    flag: "🇵🇸",
    section: "All Countries (A-Z)",
  },
  {
    code: "507",
    name: "Panama",
    iso: "PA",
    flag: "🇵🇦",
    section: "All Countries (A-Z)",
  },
  {
    code: "675",
    name: "Papua New Guinea",
    iso: "PG",
    flag: "🇵🇬",
    section: "All Countries (A-Z)",
  },
  {
    code: "595",
    name: "Paraguay",
    iso: "PY",
    flag: "🇵🇾",
    section: "All Countries (A-Z)",
  },
  {
    code: "51",
    name: "Peru",
    iso: "PE",
    flag: "🇵🇪",
    section: "All Countries (A-Z)",
  },
  {
    code: "1787",
    name: "Puerto Rico",
    iso: "PR",
    flag: "🇵🇷",
    section: "All Countries (A-Z)",
  },
  {
    code: "974",
    name: "Qatar",
    iso: "QA",
    flag: "🇶🇦",
    section: "All Countries (A-Z)",
  },
  {
    code: "262",
    name: "Réunion",
    iso: "RE",
    flag: "🇷🇪",
    section: "All Countries (A-Z)",
  },
  {
    code: "250",
    name: "Rwanda",
    iso: "RW",
    flag: "🇷🇼",
    section: "All Countries (A-Z)",
  },
  {
    code: "685",
    name: "Samoa",
    iso: "WS",
    flag: "🇼🇸",
    section: "All Countries (A-Z)",
  },
  {
    code: "378",
    name: "San Marino",
    iso: "SM",
    flag: "🇸🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "239",
    name: "São Tomé & Príncipe",
    iso: "ST",
    flag: "🇸🇹",
    section: "All Countries (A-Z)",
  },
  {
    code: "221",
    name: "Senegal",
    iso: "SN",
    flag: "🇸🇳",
    section: "All Countries (A-Z)",
  },
  {
    code: "381",
    name: "Serbia",
    iso: "RS",
    flag: "🇷🇸",
    section: "All Countries (A-Z)",
  },
  {
    code: "248",
    name: "Seychelles",
    iso: "SC",
    flag: "🇸🇨",
    section: "All Countries (A-Z)",
  },
  {
    code: "232",
    name: "Sierra Leone",
    iso: "SL",
    flag: "🇸🇱",
    section: "All Countries (A-Z)",
  },
  {
    code: "1721",
    name: "Sint Maarten",
    iso: "SX",
    flag: "🇸🇽",
    section: "All Countries (A-Z)",
  },
  {
    code: "386",
    name: "Slovenia",
    iso: "SI",
    flag: "🇸🇮",
    section: "All Countries (A-Z)",
  },
  {
    code: "677",
    name: "Solomon Islands",
    iso: "SB",
    flag: "🇸🇧",
    section: "All Countries (A-Z)",
  },
  {
    code: "252",
    name: "Somalia",
    iso: "SO",
    flag: "🇸🇴",
    section: "All Countries (A-Z)",
  },
  {
    code: "94",
    name: "Sri Lanka",
    iso: "LK",
    flag: "🇱🇰",
    section: "All Countries (A-Z)",
  },
  {
    code: "590",
    name: "St. Barthélemy",
    iso: "BL",
    flag: "🇧🇱",
    section: "All Countries (A-Z)",
  },
  {
    code: "1869",
    name: "St. Kitts & Nevis",
    iso: "KN",
    flag: "🇰🇳",
    section: "All Countries (A-Z)",
  },
  {
    code: "1758",
    name: "St. Lucia",
    iso: "LC",
    flag: "🇱🇨",
    section: "All Countries (A-Z)",
  },
  {
    code: "590",
    name: "St. Martin",
    iso: "MF",
    flag: "🇲🇫",
    section: "All Countries (A-Z)",
  },
  {
    code: "508",
    name: "St. Pierre & Miquelon",
    iso: "PM",
    flag: "🇵🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "1784",
    name: "St. Vincent & Grenadines",
    iso: "VC",
    flag: "🇻🇨",
    section: "All Countries (A-Z)",
  },
  {
    code: "597",
    name: "Suriname",
    iso: "SR",
    flag: "🇸🇷",
    section: "All Countries (A-Z)",
  },
  {
    code: "4779",
    name: "Svalbard & Jan Mayen",
    iso: "SJ",
    flag: "🇸🇯",
    section: "All Countries (A-Z)",
  },
  {
    code: "886",
    name: "Taiwan",
    iso: "TW",
    flag: "🇹🇼",
    section: "All Countries (A-Z)",
  },
  {
    code: "992",
    name: "Tajikistan",
    iso: "TJ",
    flag: "🇹🇯",
    section: "All Countries (A-Z)",
  },
  {
    code: "255",
    name: "Tanzania",
    iso: "TZ",
    flag: "🇹🇿",
    section: "All Countries (A-Z)",
  },
  {
    code: "670",
    name: "Timor-Leste",
    iso: "TL",
    flag: "🇹🇱",
    section: "All Countries (A-Z)",
  },
  {
    code: "228",
    name: "Togo",
    iso: "TG",
    flag: "🇹🇬",
    section: "All Countries (A-Z)",
  },
  {
    code: "690",
    name: "Tokelau",
    iso: "TK",
    flag: "🇹🇰",
    section: "All Countries (A-Z)",
  },
  {
    code: "676",
    name: "Tonga",
    iso: "TO",
    flag: "🇹🇴",
    section: "All Countries (A-Z)",
  },
  {
    code: "1868",
    name: "Trinidad & Tobago",
    iso: "TT",
    flag: "🇹🇹",
    section: "All Countries (A-Z)",
  },
  {
    code: "216",
    name: "Tunisia",
    iso: "TN",
    flag: "🇹🇳",
    section: "All Countries (A-Z)",
  },
  {
    code: "993",
    name: "Turkmenistan",
    iso: "TM",
    flag: "🇹🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "1649",
    name: "Turks & Caicos Islands",
    iso: "TC",
    flag: "🇹🇨",
    section: "All Countries (A-Z)",
  },
  {
    code: "688",
    name: "Tuvalu",
    iso: "TV",
    flag: "🇹🇻",
    section: "All Countries (A-Z)",
  },
  {
    code: "1340",
    name: "U.S. Virgin Islands",
    iso: "VI",
    flag: "🇻🇮",
    section: "All Countries (A-Z)",
  },
  {
    code: "256",
    name: "Uganda",
    iso: "UG",
    flag: "🇺🇬",
    section: "All Countries (A-Z)",
  },
  {
    code: "598",
    name: "Uruguay",
    iso: "UY",
    flag: "🇺🇾",
    section: "All Countries (A-Z)",
  },
  {
    code: "678",
    name: "Vanuatu",
    iso: "VU",
    flag: "🇻🇺",
    section: "All Countries (A-Z)",
  },
  {
    code: "379",
    name: "Vatican City",
    iso: "VA",
    flag: "🇻🇦",
    section: "All Countries (A-Z)",
  },
  {
    code: "58",
    name: "Venezuela",
    iso: "VE",
    flag: "🇻🇪",
    section: "All Countries (A-Z)",
  },
  {
    code: "681",
    name: "Wallis & Futuna",
    iso: "WF",
    flag: "🇼🇫",
    section: "All Countries (A-Z)",
  },
  {
    code: "967",
    name: "Yemen",
    iso: "YE",
    flag: "🇾🇪",
    section: "All Countries (A-Z)",
  },
  {
    code: "260",
    name: "Zambia",
    iso: "ZM",
    flag: "🇿🇲",
    section: "All Countries (A-Z)",
  },
  {
    code: "263",
    name: "Zimbabwe",
    iso: "ZW",
    flag: "🇿🇼",
    section: "All Countries (A-Z)",
  },
  {
    code: "687",
    name: "新喀里多尼亚",
    iso: "NCL",
    flag: "🌐",
    section: "All Countries (A-Z)",
  },
];

/**
 * Ready-to-use SelectOption list for the custom Select component with sections, flags, and dial badges.
 */
export const COUNTRY_SELECT_OPTIONS: SelectOption[] = ALL_COUNTRIES_ORDERED.map(
  (c) => ({
    id: `${c.code}-${c.iso}`,
    section: c.section,
    textValue: `${c.flag} ${c.name} (+${c.code})`,
    label: (
      <div className="flex items-center justify-between w-full gap-2 text-left">
        <span className="truncate">
          {c.flag} {c.name}
        </span>
        <span className="text-xs text-muted-foreground font-mono shrink-0">
          +{c.code}
        </span>
      </div>
    ),
  }),
);

export function cleanCountryCode(input: string): string {
  if (!input) return "1";
  const cleaned = input.replace(/[^0-9]/g, "");
  return cleaned || "1";
}

export function getDefaultCountryCodeForRegion(regionId: string): string {
  switch (regionId) {
    case "eu":
      return "49"; // Western Europe (Germany)
    case "we":
      return "7"; // Eastern Europe (Kazakhstan / Russia)
    case "us":
    case "ue":
      return "1"; // USA / Canada
    case "cn":
      return "86"; // China
    case "in":
      return "91"; // India
    default:
      return "1";
  }
}
